version: '3'

services:
  web:
    build:
      context: ../${APP_DIR}
      dockerfile: ./Dockerfile
    command: gunicorn ${MAIN_MODULE}.wsgi:application --bind 0.0.0.0:8000 --reload
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
      - ../${APP_DIR}:/home/app/web
    expose:
      - 8000
    extra_hosts:
      - db:10.5.0.1  
    networks:
      default:
        ipv4_address: 10.1.10.31
      vpcbr:
        ipv4_address: 10.5.0.7
  nginx:
    build: ../nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    ports:
      - 81:80
    depends_on:
      - web
    networks:
      default:
        ipv4_address: 10.1.10.32
      vpcbr:
        ipv4_address: 10.5.0.6

volumes:
  static_volume:
  media_volume:

networks:
  default:
    external:
      name: sa_db_nw
  vpcbr:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
