version: '3'

services:
  web:
    build:
      context: ../${APP_DIR}
      dockerfile: ./Dockerfile.prod
    command: gunicorn ${MAIN_MODULE}.wsgi:application --bind 0.0.0.0:8000 --reload
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    expose:
      - 8000
    networks:
      default:
        ipv4_address: 10.1.10.31

  nginx:
    build: ../nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    ports:
      - 81:80
    depends_on:
      - web
    networks:
      default:
        ipv4_address: 10.1.10.32

volumes:
  static_volume:
  media_volume:

networks:
  default:
    external:
      name: sa_db_nw
